tool:
  compute:
    arm64:
      enable: true
      spot: true
      instance_types:
        - m6g
tasks:
  lipidannotation:
    type: RMarkdown
    config:
      script: /app/annotateLipids.Rmd
      output_folder: /app/Output
      upload_output_folder: true
      upload_output_zip: false
      zip_filename: Output
      input_mapping:
        input_files: input_files
    autoscaling:
      default:
        ram:
          base: 7200
          max: 389120
        vcpu:
          base: 2
          max: 96
          density:
            fast: 999

  originalwf:
    type: RMarkdown
    config:
      script: /app/workflow_LipidMS.Rmd
      output_folder: /app/Output
      upload_output_folder: true
      upload_output_zip: false
      zip_filename: Output
      input_mapping:
        input_files: input_files
        metadata: metadata
    autoscaling:
      default:
        ram:
          base: 0
          max: 250000
          multipliers:
            vcpu: 3800
        vcpu:
          base: 8
          max: 64
          multipliers:
            num_files:
            - value: 0
              inputs:
                - input_files

  fameta:
    type: RMarkdown
    config:
      script: /app/workflow_FAMetA.Rmd
      output_folder: /app/Output
      upload_output_folder: true
      upload_output_zip: false
      zip_filename: Output
      input_mapping:
        input_table: input_table
    autoscaling:
      default:
        ram:
          base: 0
          max: 250000
          multipliers:
            vcpu: 3800
        vcpu:
          base: 2
          max: 64

